### ISSUE TITLE
VillainsRule

### ISSUE THREAD

**Issue by Hankypoo7** [Hankypoo7/Blooket-hacks-Hankypoo7-#105]
lol jude invited me to be a collaborator.should I delete all the hacks. Even though he might repost them again?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 No dont

**Comment by VillainsRule4000** [comment]
@Hankypoo7 They're Schoolcheats, I would.

**Comment by VillainsRule4000** [comment]
At least unmute me

**Comment by Hankypoo7** [comment]
what?

**Comment by VillainsRule4000** [comment]
@Hankypoo7 Jude stopped me from posting issues and discussions.

**Comment by Hankypoo7** [comment]
me too

**Comment by VillainsRule4000** [comment]
@Hankypoo7 YOU'RE NO LONGER A COLLAB?

**Comment by VillainsRule4000** [comment]
@Tech219 We need to talk on Discord later, I'm a little busy rn.

**Comment by 123345666777777777777777777777777** [comment]
@VillainsRule4000 can u give me ur discord?

**Comment by VillainsRule4000** [comment]
@123345666777777777777777777777777 I don't have one, why?

**Comment by VillainsRule4000** [comment]
@Hankypoo7 I still want you to respond, just want to keep this to us.

**Comment by Hankypoo7** [comment]
wait what

**Comment by VillainsRule4000** [comment]
I'm sorry you got demoted. I know own this one, at least WE give credit to Schoolcheats.

**Comment by Snowflake-Coder-H2o** [comment]
@VillainsRule4000 we GIve credits where its due. If Its ours then we dont give credits if its theirs we give credits.

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o I know.

**Comment by VillainsRule4000** [comment]
@Hankypoo7 lol-jude is now pretending to be Glixzzy. This is INSANE.

**Comment by Snowflake-Coder-H2o** [comment]
Wait what @VillainsRule4000 ?

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o @lol-jude renamed himself and is now @glixxzzy. Imagine impersonating lol...

**Comment by Snowflake-Coder-H2o** [comment]
@VillainsRule4000 LMAO. I can try and talk to him but I doubt im going to be able to.

**Comment by Hankypoo7** [comment]
yeah
