### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Kxinghello** [Hankypoo7/Blooket-hacks-Hankypoo7-#12]
You have 1 day to take down or delete or remove the hack from this repository before I let Zastix know to file a DMCA violation.

**Comment by ZasticBradyn** [comment]
You dont need to take the repository down, just please credit me. (sorry abt kxing, he hates it when ppl use are code)

**Comment by Hankypoo7** [comment]
uh ok

**Comment by Hankypoo7** [comment]
I gave credit

**Comment by ZasticBradyn** [comment]
thanks.
