### ISSUE TITLE
Minify instead of obfuscate

### ISSUE THREAD

**Issue by qaiik** [Hankypoo7/Blooket-hacks-Hankypoo7-#121]

**Comment by qaiik** [comment]
In my code, it seems you have obfuscated it. I’m not sure if this has an exact reason, but minification would certainly shorten the code, and make bookmarking easier. If you need any help doing this, you can ask me.

**Comment by VillainsRule4000** [comment]
@qaiik Hello! I'm a contributor, and my main task is to answer these issues. We obfuscate to protect code from any copycats. I think that you should add some credit (like Glixzzy did), to make the obfuscation worth it.

**Comment by qaiik** [comment]
That is understandable. Code can't be edited really well with obfuscation. I just have one warning about my scripts, and that is that you need to run mine on the join or nickname page, not in a game.
There is a fix however, and it is better.
You can run it in a game, and then use this script.

javascript:function%20get%28%29%7Breturn%20Object.values%28document.querySelector%28%22%23app%20%3E%20div%20%3E%20div%22%29%29%5B1%5D.children%5B1%5D._owner.stateNode.state.question.correctAnswers%5B0%5D%7D

I know it is kind-of complicated, but that is currently the best I can do.

**Comment by qaiik** [comment]
Also, I have decided that I will be keeping my code unobfuscated (in my repo, you can do whatever in yours), but adding a script that does credit, obfuscating that, and putting it at the bottom.

The reason I am not obfuscating the whole thing is just because it was very hard for me to get into blooket hacking, because all the code was obfuscated, and I had no idea how things were done. Believe it or not, I didn't even use react data up until zastix told me about it just a bit ago.

Thus, by leaving my code unobfuscated, people can understand how blooket hacking works.

**Comment by VillainsRule4000** [comment]
@qaiik The reason why Glixzzy hides the credit in the middle is so that people can't just remove that one line.

**Comment by v8f** [comment]
Interesting

**Comment by v8f** [comment]
Working on minifying the code since it needs to be shortened. If you have a low end device or it lags when you copy , this will make less lag or other problem.

**Comment by qaiik** [comment]
By the way, you can remove the bottom credit if you want.

**Comment by qaiik** [comment]
On the deceptive dino hacks

**Comment by VillainsRule4000** [comment]
@qaiik We wouldn't dare...
