### ISSUE TITLE
Tokens/XP hack not working

### ISSUE THREAD

**Issue by Instinct-YT** [Hankypoo7/Blooket-hacks-Hankypoo7-#127]
I dont know where to do it. I have followed each step and it wont give me tokens. 
Can someone tell me where to do it?

**Comment by VillainsRule4000** [comment]
@Instinct-YT What page are you applying the script on?

**Comment by glixxzzy** [comment]
The most likely thing is you have hit the daily cap of tokens.

**Comment by VillainsRule4000** [comment]
@glixxzzy Hi! Nice to see lol-jude here, faker...

**Comment by Snowflake-Coder-H2o** [comment]
@VillainsRule4000 is this accually gliz?

**Comment by VillainsRule4000** [comment]
@Snowflake-Coder-H2o No, faker gliz.

**Comment by VillainsRule4000** [comment]
Closed due to inactive member.
