### ISSUE TITLE
You didn’t make the Deceptive Dinos Hack. I made it.

### ISSUE THREAD

**Issue by rxzyx** [Hankypoo7/Blooket-hacks-Hankypoo7-#129]
Hello! I noticed that the hack for Deceptive Dinos is actually my hack… Can you please give me credit? Thank you for your time

**Comment by rxzyx** [comment]
Just for evidence, go on my repository and you will notice that the deceptive dino hacks are the same text and they are the same file size. And I made mine 19 days ago, while you made yours 1 day ago.

**Comment by rxzyx** [comment]
GetFossils is my Fossil Hack and FossilMultiplier is my Fossil Multiplier.

**Comment by rxzyx** [comment]
As the evidence was staten, if you do not comply with giving me credit on both your README.md and for the DeceptiveDinos README.md then I will have no choice but to issue a DMCA Takedown.

**Comment by VillainsRule4000** [comment]
@rxzyx Hello! We'll look into the source today and I'll be back in five minutes with a result.

**Comment by VillainsRule4000** [comment]
@rxzyx I looked, and the Pull Request was opened by @ghost with no credit given. I believe you, so I will give full credit. Thank you for letting us know!

**Comment by rxzyx** [comment]
Thank you for your time. I consider the issue on this repository closed.

**Comment by VillainsRule4000** [comment]
@rxzyx BTW, Your Blook Rush hacks might have been copied by @glixxzzy, who is a fake gliz copy.

**Comment by VillainsRule4000** [comment]
@rxzyx Also, @glixxzzy aka fake gliz 💀 closed your issue...

**Comment by rxzyx** [comment]
Nope I just made my own Blook Rush hack. But he also took my deceptive-dinos hack and closed my issue saying that it was stolen. (also I had no idea he was a fake lol, so many of them)

**Comment by VillainsRule4000** [comment]
@rxzyx I can't talk on his repo, bc he muted me for saying he was a faker. He's actually @lol-jude, who, to escape yelling that he copied from Schoolcheats, made himself look like gliz. Gliz actually has one x, but many do not know this.

**Comment by rxzyx** [comment]
Oh really? I remember that lol-jude guy ahahaha. Ik that gliz had one x but I thought his account was taken down or something...

**Comment by rxzyx** [comment]
Funny how the fake gliz had a 'not planned' tag. I'll wait one day and if he does not respond to me on Discord or GitHub then I will DMCA Takedown his repo.

**Comment by VillainsRule4000** [comment]
@rxzyx That would be nice, some actual investigation. I reported him from like 10 different Github accounts. Hopefully a DCMA will act. lol-jude as gliz wouldn't DARE say that someone else made a hack, boom, exposed. Then again, lol-jude tried to DCMA someone for "copying his hacks" which were taken off Schoolcheats! (see @GlixzzyBlooketHacks for this laugh, another fake gliz)

**Comment by rxzyx** [comment]
Yeah ik lol-jude, I saw issues saying that he stole the hack. And it was really blatant that he did, I don't see why it's so hard to say that it was made by someone else...

**Comment by VillainsRule4000** [comment]
@rxzyx Because glixzzy can code, and this faker can't.

**Comment by rxzyx** [comment]
I used to (still do but not as much) make hacks for android games, there was this really popular one I made and man It grew quick, and then similar thing loads of skids came but I dealt with them, I just noticed them and asked them coding questions not possible to find on Google. But this person 'jude' just doesn't want to answer or reply at all...

**Comment by VillainsRule4000** [comment]
@rxzyx That's a clever solution, coding questions NOT on Google.

**Comment by rxzyx** [comment]
Ye (fyi u forgot to give credit for crypto hack lol)

**Comment by rxzyx** [comment]
Lol I gave him a chance and then I got banned on his Discord, then I trolled and tricked him to giving image perms and got banned again LOLOLOL

**Comment by VillainsRule4000** [comment]
I am working on a new README, credit will be there.

**Comment by rxzyx** [comment]
Alright. And apparently I'm unable to do a DMCA Takedown as you are allowed to distribute other peoples code as long as you also they have an MIT License and so do you.

**Comment by VillainsRule4000** [comment]
@rxzyx Sad that @glixxzzy is too much of an idiot to even give credit.
