### ISSUE TITLE
How does the SpoofBlooks work?

### ISSUE THREAD

**Issue by FireyKitKat** [Hankypoo7/Blooket-hacks-Hankypoo7-#131]
I tried it but its not working

https://user-images.githubusercontent.com/106935277/173708661-94ae4a62-a767-4327-abf7-4cfabccc9c55.mp4

**Comment by VillainsRule4000** [comment]
Hello, @FireyKitKat!
Welcome to our Blooket Hacks!
I have identified and fixed the issue.
In the future, click a Blook to activate the cheat.

If this cheat continues to have issues, please let us know.
Thanks,
VillainsRule

**Comment by FireyKitKat** [comment]
Its still not working

https://user-images.githubusercontent.com/106935277/173709938-2aab4618-a94a-4ef5-990a-259f3b727bbb.mp4
