### ISSUE TITLE
SpoofBlooks still not working

### ISSUE THREAD

**Issue by FireyKitKat** [Hankypoo7/Blooket-hacks-Hankypoo7-#132]
i tried it again and no result...

https://user-images.githubusercontent.com/106935277/173710221-b3f2e04a-14f9-4b34-8dc1-1ec7cca78cc8.mp4

**Comment by VillainsRule4000** [comment]
This appears to be a glitched hack. I will work on the issue currently.

**Comment by FireyKitKat** [comment]
ok

**Comment by RatioBozoIDIe** [comment]
OH NOO I HOPE THE HACK GETS FIXED SOON!!!!!!

**Comment by VillainsRule4000** [comment]
> I'm try to fix it...

Hello! That would be nice, post any results in the Discussions!
