### ISSUE TITLE
Hanky

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Hankypoo7/Blooket-hacks-Hankypoo7-#18]
Hey, can we make a real Blooket hack repo? It will be even more organized and there will be better hacks and we will update them often. becasue this is basically just old hacks and not new ones. I can make the repo and let you contribute but I will probally do most of the hacks and stuff. Because I like making the stuff. I will organize it. I will give better description of all of the hacks. If not its completely fine.

**Comment by Hankypoo7** [comment]
can we change this one to the more orginised one so that people know where to go but I could maybe transfer ownership to you

**Comment by Snowflake-Coder-H2o** [comment]
Ok thats fine. YOu can transfer ownership.

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 So I will update the readme.md and say whats will be happening. Is that fine?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 you there?

Have a great day!

-Snow

**Comment by Hankypoo7** [comment]
sorry i got shool i will talk to you later

**Comment by Hankypoo7** [comment]
cant you do all that stuff without ownership?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Yes but it will be much easier  I can transfer ownership back whenever everything is setup the right way

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
transfer it back when it set up ok?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Ok it might be a couple days though

**Comment by Hankypoo7** [comment]
it says you cant unless you delete the thing you forked from it

**Comment by Hankypoo7** [comment]
i gtg ill be back later

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Does it say I forked something?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Try to transfer ownership now?

**Comment by Hankypoo7** [comment]
yeah

**Comment by Hankypoo7** [comment]
i did it but transfer it back when your done ok?

**Comment by Snowflake-Coder-H2o** [comment]
Tranfer owner ship becuase Im not owner of the repo rn?

**Comment by Hankypoo7** [comment]
i did

**Comment by Hankypoo7** [comment]
i sent the invite

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Did you type Snowflake-Coder-H2o 
?
You have to make sure you type my name right.

**Comment by colbymcdaniel** [comment]
hay sorry for not responding I lost my Chromebook

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel wym sorry for not responding

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Who did?

**Comment by Snowflake-Coder-H2o** [comment]
oh yeah I pinged you a couple days ago because I was telling people know that I was closing an issue

**Comment by colbymcdaniel** [comment]
ok then

**Comment by Snowflake-Coder-H2o** [comment]
yeah

**Comment by colbymcdaniel** [comment]
I can't talk my teacher wot let me

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel wym?

**Comment by Hankypoo7** [comment]
he in class

**Comment by Hankypoo7** [comment]
try to do it without ownership

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  ok I'm back

**Comment by Hankypoo7** [comment]
hi

**Comment by colbymcdaniel** [comment]
how have you been

**Comment by Hankypoo7** [comment]
good, you?

**Comment by Hankypoo7** [comment]
im working ona a new hack to add 499 tokens

**Comment by colbymcdaniel** [comment]
by

**Comment by colbymcdaniel** [comment]
and I'm good

**Comment by colbymcdaniel** [comment]
I'm back guys hello guys how have yall been?

**Comment by colbymcdaniel** [comment]
I have discord its just on my phone not this because its a school Chromebook

**Comment by colbymcdaniel** [comment]
just wanted yall to know

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Same.

**Comment by Hankypoo7** [comment]
I dont have discord lol sorry

**Comment by colbymcdaniel** [comment]
if yall want to use discord on your guy's phone my discord is cheese man ill have to check to see what the number thing that you need i can check at like 3:30

**Comment by colbymcdaniel** [comment]
hay yall hows yall's day going (I'm talking in Floridian btw)

**Comment by Hankypoo7** [comment]
good you?

**Comment by colbymcdaniel** [comment]
I'm doing good I'm doing a story of Baba Yaga

**Comment by Hankypoo7** [comment]
nice

**Comment by colbymcdaniel** [comment]
yeah

**Comment by colbymcdaniel** [comment]
@Hankypoo7  hay witch thing should we talk on

**Comment by Hankypoo7** [comment]
or https://github.com/Hankypoo7/Blooket-hacks-Hankypoo7-/issues/20

**Comment by Snowflake-Coder-H2o** [comment]
Have a great day!

-Snow
