### ISSUE TITLE
@snowflake

### ISSUE THREAD

**Issue by Hankypoo7** [Hankypoo7/Blooket-hacks-Hankypoo7-#19]
can you make the add tokens blooket hack add 499 tokens instead of 500, it is leading to get people banned, becuase there is now a new antichant for adding 500 tokens in one

**Comment by Hankypoo7** [comment]
ok thanks

**Comment by Hankypoo7** [comment]
paste it here when you finish

**Comment by Hankypoo7** [comment]
@Snowflake-Coder-H2o hows it going

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Good but I jsut found out that zastic wont be really making hacks for blooket that much anymore and for now neither will I. Or at least until things calm down.

**Comment by Hankypoo7** [comment]
ok but did you fix it

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Fix the repo?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 I said prior, Im currently not working on any hacks until things calm down. @Hankypoo7

**Comment by Hankypoo7** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
Im dealing with legal things atm. I will be back with hacks in a couple days.

**Comment by Snowflake-Coder-H2o** [comment]
Have a great day!

-Snow

**Comment by Hankypoo7** [comment]
wait tell me who and why and how

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 What do you mean? 
Have a great day!

-Snow

**Comment by Hankypoo7** [comment]
who is legally threataning you

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 The old legend, Gliz.He made me delete a whole entire repo. Thats why my hacks are gone. So I will be remaking my own hacks.

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
Have a great day!

-Snow
