### ISSUE TITLE
Some broken gamemode hacks

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [Hankypoo7/Blooket-hacks-Hankypoo7-#20]
None of the game mode hacks work for me why.Ps.I am on I.pad.

**Comment by Hankypoo7** [comment]
ok. We will try to work on a fix in the next day or sooner. thanks for the issue

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7  will try

**Comment by Hankypoo7** [comment]
yeah

**Comment by 123345666777777777777777777777777** [comment]
TYSSM

**Comment by Hankypoo7** [comment]
yeah ofc :)

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 What hacks are broken so I know and so I can work on fixing them. 
Have a great day!

-Snow

**Comment by Hankypoo7** [comment]
@Snowflake-Coder-H2o  spam open boxes

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Ok Ill be trying to fix it

**Comment by 123345666777777777777777777777777** [comment]
Have u fixed the broken game mode hacks?

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 Sorry man but we are currently working on it.

**Comment by Hankypoo7** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 What do you mean by "flex"?

**Comment by 123345666777777777777777777777777** [comment]
Flex means to show off

**Comment by Snowflake-Coder-H2o** [comment]
o

**Comment by 123345666777777777777777777777777** [comment]
Did you fix these?

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777

**Comment by 123345666777777777777777777777777** [comment]
Wut @Snowflake-Coder-H2o

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey guys what is broken

**Comment by isthatyourfaceoryouassicanttell** [comment]
i can do it

**Comment by isthatyourfaceoryouassicanttell** [comment]
123345666777777777777777777777777777777777777777 i can fix what ever you need
