### ISSUE TITLE
OMG TYSM!!!!!!

### ISSUE THREAD

**Issue by BlooketisLit** [Hankypoo7/Blooket-hacks-Hankypoo7-#26]
THEESE ACTUALLY WORK THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU!!!!!!!!!

**Comment by Hankypoo7** [comment]
yeah man np its what we do :)

**Comment by Snowflake-Coder-H2o** [comment]
@BlooketisLit Its what we all do. We make and post them
