### ISSUE TITLE
Fishing Frenzy

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [Hankypoo7/Blooket-hacks-Hankypoo7-#28]
Most people in my class like to play Fishing Frenzy and Crypto hack.It would be nice if you made hacks for both of those.Crypto does not work.

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 Ok.

**Comment by 123345666777777777777777777777777** [comment]
Oh you are very fast

**Comment by 123345666777777777777777777777777** [comment]
At responding

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 I try to be
