### ISSUE TITLE
its working well thank you so much i appreciate the work you have done 

### ISSUE THREAD

**Issue by isthatyourfaceoryouassicanttell** [Hankypoo7/Blooket-hacks-Hankypoo7-#3]

**Comment by Hankypoo7** [comment]
yeah man np

**Comment by Hankypoo7** [comment]
wait just a question tho where did you find my page just wondering

**Comment by isthatyourfaceoryouassicanttell** [comment]
i found it on glizzes last scrip thing and is took me to schoolcheats.net
witch is blocked lol but it was advertised in the comments

**Comment by Hankypoo7** [comment]
ok thanks
