### ISSUE TITLE
THANKS!

### ISSUE THREAD

**Issue by wagma9g9q** [Hankypoo7/Blooket-hacks-Hankypoo7-#34]
These hacks are awesome!

**Comment by 123345666777777777777777777777777** [comment]
It works for me and it is very good.

**Comment by 123345666777777777777777777777777** [comment]
Also it literally says some of these are from schoolcheats.net it’s in the README.

**Comment by Snowflake-Coder-H2o** [comment]
@ghost go away

**Comment by VillainsRule4000** [comment]
@Hankypoo7 seriously?
