### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by isthatyourfaceoryouassicanttell** [Hankypoo7/Blooket-hacks-Hankypoo7-#4]
can you work on a ixl hack to get all questions correct

**Comment by Hankypoo7** [comment]
yeah, it might take a while tho, I bet I can get it done by tonight.

**Comment by isthatyourfaceoryouassicanttell** [comment]
thank you so much you are the best freaking guy in the world   ttttttyyyyyyyyyyyy thank you !!!!!!!!!!!!!!!!!!!!!💪

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey also if you could teach me a little bit or show me a video to watch to do these things i could help you with this stuff and be your back up during school hours some times even at home might be able to help but if you could show me i vid or teach me it i will help you:)

**Comment by isthatyourfaceoryouassicanttell** [comment]
i have to go next class bye

**Comment by Hankypoo7** [comment]
bye alr sure

**Comment by Hankypoo7** [comment]
yeah bro np

**Comment by isthatyourfaceoryouassicanttell** [comment]
np ?.. sorry im still learning all of the key words
sorry gtg langauge arts bye bye

**Comment by isthatyourfaceoryouassicanttell** [comment]
no problem o got it hey after school i have about 45 m to work

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey email me here evanchristensenkunz@gmail.com for more info plz :)

**Comment by Hankypoo7** [comment]
ok. btw np means no problem

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey whats up can you email my gmail i am out of school so i have some time

**Comment by isthatyourfaceoryouassicanttell** [comment]
ha i forgot my own email lol i guess i do have 5 but here email echristensenkunz@gmail.com

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey wate  that is one of my email you can email both i saw you were emailing me

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey do you have a gmail

**Comment by isthatyourfaceoryouassicanttell** [comment]
you here?..

**Comment by isthatyourfaceoryouassicanttell** [comment]
bye i have piano lessons i will be back monday maybe sometime this weekend bye

**Comment by Hankypoo7** [comment]
ok sorry i had baseball practice

**Comment by Hankypoo7** [comment]
yeah just email back thats my email address

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey you on

**Comment by isthatyourfaceoryouassicanttell** [comment]
what in the middle of winter

**Comment by isthatyourfaceoryouassicanttell** [comment]
could you teach me how to hack

**Comment by isthatyourfaceoryouassicanttell** [comment]
or show me a video off the internet

**Comment by isthatyourfaceoryouassicanttell** [comment]
i will have to go soon and go home im at my piano lessons but my sister is
playing right now so i will read every thing you have to say later but if
teach me how to hack i will help you and i will fix anything that goes down
gtg:)

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
I just found the files online lol
Im tryna make new hacks tho by noticing what commands do what and extending their periods to create longer encrypted code.

**Comment by isthatyourfaceoryouassicanttell** [comment]
where do you find them  so i can help gtg bye

**Comment by Hankypoo7** [comment]
These are the modified versions to be easier and more accessible,
the original links are here https://github.com/Hankypoo7/blooket-hack-RESTORED

**Comment by isthatyourfaceoryouassicanttell** [comment]
hi

**Comment by Hankypoo7** [comment]
Hi

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey you on

**Comment by isthatyourfaceoryouassicanttell** [comment]
just send a message for things you need help with and then when i read them i will look for some and if i find one i will post it here

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
Imma give you perms I hope I can trust you, but make different files for the remaining game modes that we still need like factory, gold, and racing.

**Comment by Hankypoo7** [comment]
ok i sent the invite

**Comment by isthatyourfaceoryouassicanttell** [comment]
k remeber  im am a noobie a apprentice and yes you can trust me i will give you a big piece of trust i dont tell many people its so then you trust me im 12

**Comment by isthatyourfaceoryouassicanttell** [comment]
you on

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey so i added one and now it says i have to use this template to create a new repository.:(

**Comment by isthatyourfaceoryouassicanttell** [comment]
i can work this monday and this week two :)

**Comment by isthatyourfaceoryouassicanttell** [comment]
got it working :))))))))))))))))))))))))):):):):):):):)::):):):):))::):)::):):):):):):):):)

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey i put them in for you

**Comment by Hankypoo7** [comment]
ty im 12 as well so i gotchu

**Comment by isthatyourfaceoryouassicanttell** [comment]
o ha your 12 to nice wow :)

**Comment by isthatyourfaceoryouassicanttell** [comment]
colbymcdaniel i can tell you whats wrong go to the top of your blooket page and type javascript: then past the code and hit enter then refresh the page and you will have max coins and xp for the day. :):):)::):)

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey how is the ixl hack going

**Comment by Hankypoo7** [comment]
i gotchu

**Comment by Hankypoo7** [comment]
wdym ixl hack

**Comment by isthatyourfaceoryouassicanttell** [comment]
so i can get free gum yum

**Comment by isthatyourfaceoryouassicanttell** [comment]
every 5 courses I complete i get a pack of gum 1 a day

**Comment by colbymcdaniel** [comment]
What's up with gum?

**Comment by isthatyourfaceoryouassicanttell** [comment]
o and i think i got rid of steve and pazza is a good guy :) me pro :) pro :) 👍

**Comment by isthatyourfaceoryouassicanttell** [comment]
i get gum from my teacher

**Comment by colbymcdaniel** [comment]
oh ok thanks for telling me

**Comment by Hankypoo7** [comment]
lucky but like what does ixl stand for
what hack should I make?

**Comment by colbymcdaniel** [comment]
can you give me a link to the ixl hack

**Comment by Hankypoo7** [comment]
What i gtg ill be back at like 4 but what hack do you want me to make

**Comment by colbymcdaniel** [comment]
i just want the ixl one

**Comment by colbymcdaniel** [comment]
witch ixl hacks are there

**Comment by Blooket-dude** [comment]
what is an ixl hack?

**Comment by Hankypoo7** [comment]
idk

**Comment by VillainsRule4000** [comment]
what on-
