### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Hankypoo7/Blooket-hacks-Hankypoo7-#40]
@Hankypoo7 Do you have discord?

**Comment by Hankypoo7** [comment]
i do not, sorry

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey snowflake i have discord

**Comment by isthatyourfaceoryouassicanttell** [comment]
unless you have a unblocked discord i can use

**Comment by Pikachurocksinssbu** [comment]
Yes

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey pikachurocksinsbu do you play call of duty warzone or vanguard or minecraft  or Ark survival evolved

**Comment by isthatyourfaceoryouassicanttell** [comment]
gtg bye

**Comment by Pikachurocksinssbu** [comment]
Nope

**Comment by Pikachurocksinssbu** [comment]
Bye

**Comment by colbymcdaniel** [comment]
I have discord Minecraft and call of duty vanguard if you want to play @isthatyourfaceoryouassicanttell
