### ISSUE TITLE
unlock all blooks dosent work

### ISSUE THREAD

**Issue by Brayden9292** [Hankypoo7/Blooket-hacks-Hankypoo7-#41]

**Comment by Snowflake-Coder-H2o** [comment]
It might be a day or two.

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey got you

**Comment by isthatyourfaceoryouassicanttell** [comment]
snowflake i can do it

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell Ight

**Comment by Hankypoo7** [comment]
thank you

**Comment by Tech219** [comment]
This problem seems to happen currently for me. I don't know why??

**Comment by Tech219** [comment]
That's why I opened it back up . @VillainsRule4000 Can you test the script for me really quick? Tell me details in console

**Comment by VillainsRule4000** [comment]
@Tech219 I actually care about my alts being banned...but I'll use a VPN and a guest session being hosted from an alt (that's how to test a hack BTW).

**Comment by VillainsRule4000** [comment]
@Brayden9292 @Tech219 It was the second line of code; the hack is fixed now!
