### ISSUE TITLE
Crypto Hack

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [Hankypoo7/Blooket-hacks-Hankypoo7-#46]
Can you make aa hack where you can't be hacked?

**Comment by Hankypoo7** [comment]
I'm not sure if that is possible, i can try though

**Comment by isthatyourfaceoryouassicanttell** [comment]
yea that doesn't make much sense unless you mean you can stop other people from hacking and really its just add scripts which are just codes

**Comment by 123345666777777777777777777777777** [comment]
ok

**Comment by VillainsRule4000** [comment]
This is impossible as another person would have to use the hack.
