### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Hankypoo7/Blooket-hacks-Hankypoo7-#48]
@Hankypoo7 I think we need to minimize the amount of people we have as a collaberator. We need to make @123345666777777777777777777777777 not a collaberator. becuase he dosent really need to be one. He isnt making hacks he is just showcasing them to his friends and claiming them to be his.

**Comment by Pikachurocksinssbu** [comment]
He has helped a lot by promoting these hacks.

**Comment by isthatyourfaceoryouassicanttell** [comment]
?... what do you mean

**Comment by isthatyourfaceoryouassicanttell** [comment]
how are you on here

**Comment by Pikachurocksinssbu** [comment]
I am his best friend

**Comment by isthatyourfaceoryouassicanttell** [comment]
yea and

**Comment by isthatyourfaceoryouassicanttell** [comment]
what do you mean by he promted the hacks

**Comment by Pikachurocksinssbu** [comment]
I am sitting next to him

**Comment by isthatyourfaceoryouassicanttell** [comment]
yea and my question

**Comment by Pikachurocksinssbu** [comment]
And he told almost the whole school to use the hacks.

**Comment by isthatyourfaceoryouassicanttell** [comment]
let me guess school o well be prepared for blocking

**Comment by Pikachurocksinssbu** [comment]
WDYM

**Comment by Pikachurocksinssbu** [comment]
O

**Comment by Pikachurocksinssbu** [comment]
I am in Art

**Comment by isthatyourfaceoryouassicanttell** [comment]
what state is your school in mine is in Minnasota

**Comment by isthatyourfaceoryouassicanttell** [comment]
im in 6th grade

**Comment by isthatyourfaceoryouassicanttell** [comment]
?...

**Comment by Pikachurocksinssbu** [comment]
5th

**Comment by Pikachurocksinssbu** [comment]
ILLINOIS

**Comment by isthatyourfaceoryouassicanttell** [comment]
state not town or city

**Comment by Pikachurocksinssbu** [comment]
Illinois is a state

**Comment by isthatyourfaceoryouassicanttell** [comment]
use pixel art as a excuse to be on your chromebook during art

**Comment by Pikachurocksinssbu** [comment]
Sure

**Comment by Pikachurocksinssbu** [comment]
Sure

**Comment by Pikachurocksinssbu** [comment]
I am looking at “pictures” to draw

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell @123345666777777777777777777777777 Has promoted these hacks but he dosent need to be a collaberator for this.

**Comment by isthatyourfaceoryouassicanttell** [comment]
yea

**Comment by isthatyourfaceoryouassicanttell** [comment]
i agree

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey snowflake once i get discord with you can you teach me how to make more types of hacks and could you try to make a ixl hack that shows you what the answers are

**Comment by Snowflake-Coder-H2o** [comment]
They arent @colbymcdaniel hacks either

**Comment by Snowflake-Coder-H2o** [comment]
ITs only mine @isthatyourfaceoryouassicanttell and you @Hankypoo7

**Comment by Hankypoo7** [comment]
ok

**Comment by colbymcdaniel** [comment]
i don't know how to make them privet can you tell me and i will

**Comment by colbymcdaniel** [comment]
@Hankypoo7 i don't know how to make them privet can you tell me and i will

**Comment by Hankypoo7** [comment]
make what private?

**Comment by colbymcdaniel** [comment]
yall were talking to every one to make there blanket thing privet but i don't know-how

**Comment by Hankypoo7** [comment]
not you i was telling @123345666777777777777777777777777 that he has to make his website private because he doesnt own the hacks

**Comment by 123345666777777777777777777777777** [comment]
Ok so how do I make myself not a collaborater

**Comment by isthatyourfaceoryouassicanttell** [comment]
um hank will do it i dont know how cause i dont own it
