### ISSUE TITLE
Bro WTF

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Hankypoo7/Blooket-hacks-Hankypoo7-#49]
@isthatyourfaceoryouassicanttell Dude your not codeing  your own hacks. Your getting them from schoolcheats.net/blooket. Stop we are going to get a cease and desist From Gliz. Now I know Why we are gettong targeted.

**Comment by colbymcdaniel** [comment]
what happened?

**Comment by Hankypoo7** [comment]
yeah whats going on

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7  I just figured out why we are getting copyright Striked from Gliz. It's because @isthatyourfaceoryouassicanttell Has been getting his hacks from Schoolcheats.net/blooket. I thought he has been coding then But he hasent been

**Comment by colbymcdaniel** [comment]
oh that's not good

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel  Yeah IG

**Comment by colbymcdaniel** [comment]
btw do yall have a discord

**Comment by Snowflake-Coder-H2o** [comment]
I dont know what the 4 digit numbers are though

**Comment by Snowflake-Coder-H2o** [comment]
Ok.

**Comment by colbymcdaniel** [comment]
ill tel you at around 4 ish

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Ok

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  How's your day going?

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Good! Thanks for asking! How's your day going?
-Snow

**Comment by colbymcdaniel** [comment]
good

**Comment by colbymcdaniel** [comment]
hay @Snowflake-Coder-H2o have you got to talk to isthatyourfaceoryouassicanttell and see whats up?

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Not yet he hasen't responded on here yet

**Comment by colbymcdaniel** [comment]
ok well talk to you latar

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Talk to you later

**Comment by isthatyourfaceoryouassicanttell** [comment]
no i cant use that its blocked

**Comment by isthatyourfaceoryouassicanttell** [comment]
its blocked for me i tried to get on are school has something called securly and it blocks everything

**Comment by isthatyourfaceoryouassicanttell** [comment]
sadly

**Comment by isthatyourfaceoryouassicanttell** [comment]
so i use his to fix things other wise no

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell So your using someone else hacks?

**Comment by isthatyourfaceoryouassicanttell** [comment]
i wish i could learn how to code my one yes he said i could

**Comment by isthatyourfaceoryouassicanttell** [comment]
be back soon

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell The point of this repo is to make your own hacks

**Comment by isthatyourfaceoryouassicanttell** [comment]
one sec social studies can you teach me how to make them at 10:45 to 11:10 
just make a video and private chat me it gtg bye

**Comment by colbymcdaniel** [comment]
so how has it been talking to isthatyourfaceoryouassicanttell @Snowflake-Coder-H2o

**Comment by isthatyourfaceoryouassicanttell** [comment]
colbymcdaniel I got permission from lol jude to use his so if i need to fix things that what i use

**Comment by isthatyourfaceoryouassicanttell** [comment]
is someone could teach it would be nice if somebody could email me a video and teach me here is my alt email cause my school doesnt let me talk to people out of school evanchristensenkunz@gmail.com          i will code my own hacks if i learn how to :)

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell Im not going to make a whole video just to explain how to make hacks. I thought you coded your own hacks. So Stop using lol jude's hacks because he got them from schoolcheats.net/blooket which is gliz code. That is why we are getting copyright striked. If you dont stop using his hacks I will be forced to take this into my own hands

**Comment by colbymcdaniel** [comment]
hay @isthatyourfaceoryouassicanttell i know this might not be the right time but can you tell me where the ixl hacks are

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell What is IXL

**Comment by colbymcdaniel** [comment]
can i get ixl hacks @isthatyourfaceoryouassicanttell

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel What is IXL mean

**Comment by isthatyourfaceoryouassicanttell** [comment]
IXL IS A LEARNING PLAT FORM THAT COST MONEY AND THE TEACHERS MAKE US DO IT ALL THE TIME BUT i can earn prizes sorry caps lock

**Comment by isthatyourfaceoryouassicanttell** [comment]
no i said if i could learn how i would make one

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey i am searching up how to do it and well i think i figured it out i am first going to make a ixl hack

**Comment by byronbytes** [comment]
I think crediting him for most of the scripts could remove the copyrights

**Comment by isthatyourfaceoryouassicanttell** [comment]
just leave them gtg be back soon

**Comment by isthatyourfaceoryouassicanttell** [comment]
yea

**Comment by isthatyourfaceoryouassicanttell** [comment]
@byronbytes can you make hacks or no

**Comment by Hankypoo7** [comment]
@byronbytes is helping alot by organizing all theese hacks, thanks again :)

**Comment by isthatyourfaceoryouassicanttell** [comment]
ok he is doing the organizing

**Comment by isthatyourfaceoryouassicanttell** [comment]
i have something

**Comment by byronbytes** [comment]
> @byronbytes can you make hacks or no

I mean, I have experience with coding but not in JS. You can check my profile for the stuff that I can do, I mainly do C#.

**Comment by isthatyourfaceoryouassicanttell** [comment]
@byronbytes samething try this https://www.twilio.com/quest/download
this is a JS learning plat form i just found :)

**Comment by TheVillainCoder** [comment]
@Snowflake-Coder-H2o still officially an issue? I would go through each hack (on an alt) and see if it has the Gliz credit.
