### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Hankypoo7/Blooket-hacks-Hankypoo7-#51]
@Hankypoo7 @colbymcdaniel @byronbytes @isthatyourfaceoryouassicanttell @123345666777777777777777777777777 Im making a website for the hacks. Ill post the site.

**Comment by Hankypoo7** [comment]
ok

**Comment by colbymcdaniel** [comment]
?

**Comment by byronbytes** [comment]
I could also help with the website, sounds interesting.

**Comment by isthatyourfaceoryouassicanttell** [comment]
no body worry this is @isthatyourfaceoryouassicanttell

**Comment by isthatyourfaceoryouassicanttell** [comment]
o wate

**Comment by isthatyourfaceoryouassicanttell** [comment]
seck its not working

**Comment by isthatyourfaceoryouassicanttell** [comment]
there lets see

**Comment by isthatyourfaceoryouassicanttell** [comment]
can anyone show me how to create hacks using inspect tool plz it will be worth it trust me

**Comment by Hankypoo7** [comment]
@Snowflake-Coder-H2o what kind of website? can I help?

**Comment by isthatyourfaceoryouassicanttell** [comment]
he will post it some time hey hank can you make a video for me on how to make these hacks using the inspect tool plz it will be worth the time cause once im done with chores al thou i have like 50 during my free time i will be making all sorts of hacks so Pretty plz i make a cool pixel art plz

**Comment by byronbytes** [comment]
So basically like a  bypass school block sites, I could help.

**Comment by Hankypoo7** [comment]
ok cool

**Comment by Hankypoo7** [comment]
Its hard to explain @isthatyourfaceoryouassicanttell

**Comment by byronbytes** [comment]
also I own a business at https://LiteTools.net

**Comment by isthatyourfaceoryouassicanttell** [comment]
no no no i know all about bypassing

**Comment by isthatyourfaceoryouassicanttell** [comment]
trust me 1 year and a half and me and my friend you dont know him he hasnt chatted on here but we have found 9 different ways to bypass

**Comment by isthatyourfaceoryouassicanttell** [comment]
when one gets blocked or delted then we find a new way to are stuff

**Comment by isthatyourfaceoryouassicanttell** [comment]
try this the https://spotsstuff.cf

**Comment by isthatyourfaceoryouassicanttell** [comment]
or https://sealcentral.gq

**Comment by isthatyourfaceoryouassicanttell** [comment]
https://shawdowhasalink.gq

**Comment by isthatyourfaceoryouassicanttell** [comment]
https://shawdOw.gq

**Comment by isthatyourfaceoryouassicanttell** [comment]
https://www.wevideo.com/view/2646667020
here is a bypass way

**Comment by isthatyourfaceoryouassicanttell** [comment]
never mind i cant get it to work

**Comment by isthatyourfaceoryouassicanttell** [comment]
its working yay

**Comment by isthatyourfaceoryouassicanttell** [comment]
https://www.wevideo.com/view/2646667020 here is the first method it dosnt work for me any more sadly cause school admin delted the edit button but enjoy for you guys :)

**Comment by Hankypoo7** [comment]
> also I own a business at https://LiteTools.net

Really?! thats awesome!

**Comment by isthatyourfaceoryouassicanttell** [comment]
snowflake did you make it yet

**Comment by byronbytes** [comment]
good

**Comment by colbymcdaniel** [comment]
hay guys hows yalls day going?

**Comment by 123345666777777777777777777777777** [comment]
@Snowflake-Coder-H2o

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 No Its not for this. And It wasent your idea. I was thinking bout making one way before you. I just never got the time to finish it. i have just been working on it as a side project.

**Comment by Snowflake-Coder-H2o** [comment]
ITs for my own repo.

**Comment by byronbytes** [comment]
Shouldn't you guys just make an organization for all the blooket things so it's easier to keep track of everything? You wouldn't need to have seperate repos for different users, because some of you guys have the same blooket hack repositories

**Comment by Snowflake-Coder-H2o** [comment]
@byronbytes Yes But because of Gliz He wont leave us alone therefor. If a repo gets taken down. We wont have the hacks and have to recode and I dont wanna do that.

**Comment by byronbytes** [comment]
> @byronbytes Yes But because of Gliz He wont leave us alone therefor. If a repo gets taken down. We wont have the hacks and have to recode and I dont wanna do that.

Well Gliz cheats don't even work anymore, most cheats either don't load his cheats or say that he removed them. Also, I know how to help out, do you guys have discord?

**Comment by Snowflake-Coder-H2o** [comment]
@byronbytes Yes I do Have discord.

**Comment by byronbytes** [comment]
by the way doing the scripts boots you out of the game

**Comment by Snowflake-Coder-H2o** [comment]
which ones

**Comment by byronbytes** [comment]
Gold Quest ones

**Comment by Snowflake-Coder-H2o** [comment]
Ok

**Comment by TheVillainCoder** [comment]
@Snowflake-Coder-H2o Still need open?
