### ISSUE TITLE
Use bookmarklet

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [Hankypoo7/Blooket-hacks-Hankypoo7-#58]
@Hankypoo7 do u know about the bookmarklet method

**Comment by Hankypoo7** [comment]
yeah

**Comment by 123345666777777777777777777777777** [comment]
Don’t use the one where u paste JavaScript and the code into the url box because for some devices it doesn’t work.So instead delete the url box one and make a pic of doing the bookmarklet method @Hankypoo7.

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 What is the bookmarklet method?

**Comment by 123345666777777777777777777777777** [comment]
I will tell on discord

**Comment by Snowflake-Coder-H2o** [comment]
Ok

**Comment by 123345666777777777777777777777777** [comment]
@Snowflake-Coder-H2o u accidentally blocked me on discord

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 No I didnt "accidentally" I purposely blocked you. You were being anoyying.

**Comment by 123345666777777777777777777777777** [comment]
Whoops srry

**Comment by 123345666777777777777777777777777** [comment]
Lol
