### ISSUE TITLE
I need help with pasting the code

### ISSUE THREAD

**Issue by Hankypoo7** [Hankypoo7/Blooket-hacks-Hankypoo7-#6]

**Comment by Hankypoo7** [comment]
wdym ixl

**Comment by isthatyourfaceoryouassicanttell** [comment]
o yea ixl every day if i get 5 80 and higher i get a pack of gum the teacher has watermelon the best one

**Comment by isthatyourfaceoryouassicanttell** [comment]
and you don't need more people to run the page if we start getting behind i have a friend who gets OUT OF SCHOOL IN THE MIDDLE OF THE DAY i don't know how he does it he makes some excuse and calls his mom who picks him up and then he is free all day so he can help to if we start falling behind also is there anything else you need done just let me know

**Comment by Hankypoo7** [comment]
dang, ok thanks

**Comment by colbymcdaniel** [comment]
what  happened with the coins and exp

**Comment by Hankypoo7** [comment]
sorry its back now, we needed a quick fix

**Comment by Hankypoo7** [comment]
this guy biggiesteve is threatening me becuase I "Used his hacks" so the get tokens and xp is down and as well as the sell dupe blooks

**Comment by isthatyourfaceoryouassicanttell** [comment]
where at

**Comment by isthatyourfaceoryouassicanttell** [comment]
o thats not true

**Comment by isthatyourfaceoryouassicanttell** [comment]
i know where we get those hacks from and thats not it

**Comment by Hankypoo7** [comment]
ye their back up thanks bro

**Comment by colbymcdaniel** [comment]
he better not be threatening you bro you don't know who i am tho

**Comment by colbymcdaniel** [comment]
ignore the second part

**Comment by colbymcdaniel** [comment]
thanks for the exp fix btw

**Comment by Hankypoo7** [comment]
yeah

**Comment by Hankypoo7** [comment]
are you isthatyourfaceoryouassicanttells friend?

**Comment by colbymcdaniel** [comment]
no I just like what yall are doing

**Comment by Hankypoo7** [comment]
ok

**Comment by Blooket-dude** [comment]
@colbymcdaniel @isthatyourfaceoryouassicanttell @Hankypoo7 dont talk about people behind their backs!
