### ISSUE TITLE
Choice ESP in Gold Quest

### ISSUE THREAD

**Issue by TheVillainCoder** [Hankypoo7/Blooket-hacks-Hankypoo7-#60]
What is the function of this hack?

**Comment by Hankypoo7** [comment]
it shows what you get if you click on any given chest

**Comment by TheVillainCoder** [comment]
Thank you! Maybe you could change the name to something more obvious?

**Comment by Snowflake-Coder-H2o** [comment]
@TheVillainCoder I gotchu
