### ISSUE TITLE
Gold Rush Directory

### ISSUE THREAD

**Issue by TheVillainCoder** [Hankypoo7/Blooket-hacks-Hankypoo7-#63]
There is a Directory titled 'Gold Rush'. The actual gamemode is 'Gold Quest'.
### _Tags_
_@Hankypoo7 
@Snowflake-Coder-H2o 
@isthatyourfaceoryouassicanttell_

**Comment by Snowflake-Coder-H2o** [comment]
@TheVillainCoder Thanks Ill fix it
