### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by bigguystevieb1** [Hankypoo7/Blooket-hacks-Hankypoo7-#7]
@Hankypoo7. This will get very serious if you don't delete your "max xp and tokens" and "spam open boxes" hacks because i did Ctrl + F and copied my hacks onto ur script and those 2 hacks were mine. If you don't delete, I will make this a very serious issue.

**Comment by bigguystevieb1** [comment]
@Hankypoo7

**Comment by Hankypoo7** [comment]
ok
