### ISSUE TITLE
kicked

### ISSUE THREAD

**Issue by TheDItto** [Hankypoo7/Blooket-hacks-Hankypoo7-#77]
when you use the add tokens and then do something it kicks you. And this is for all of them.

**Comment by Hankypoo7** [comment]
ok we will check it out

**Comment by Hankypoo7** [comment]
I tested the tokens and it didn't kick me

**Comment by TheVillainCoder** [comment]
@Hankypoo7 They mean the ones for in-game (such as Gold Quest/Infinite Gold.js)

**Comment by TheVillainCoder** [comment]
@Hankypoo7 @TheDItto We are saying 'Kick' as in you can't log in?

**Comment by 123345666777777777777777777777777** [comment]
No,as in it sends you back to game pin screen

**Comment by TheDItto** [comment]
yes and i got suspended but it is fine I got alts

**Comment by TheVillainCoder** [comment]
@TheDItto hack on your alts instead :)
