### ISSUE TITLE
  .

### ISSUE THREAD

**Issue by bigguystevieb1** [Hankypoo7/Blooket-hacks-Hankypoo7-#8]
I'm getting legal consequences put against you if you don't delete them.

**Comment by bigguystevieb1** [comment]
@Hankypoo7

**Comment by Hankypoo7** [comment]
i got the scripts from schoolcheats

**Comment by Hankypoo7** [comment]
dude fine whatever but can I atleast give you credit and use them

**Comment by isthatyourfaceoryouassicanttell** [comment]
yea and also we didn't copy wright we have permission i know all  of these people that i get these from there my friends hanky doesn't know them all but i do

**Comment by bigguystevieb1** [comment]
> dude fine whatever but can I atleast give you credit and use them

No take them down, I gave you a chance but u didn't use it so ur done.

**Comment by bigguystevieb1** [comment]
@Hankypoo7

**Comment by isthatyourfaceoryouassicanttell** [comment]
no what are you going to do

**Comment by pazza223** [comment]
@bigguystevieb1 did you make the hacks or know how made them? your text/comments looks like you are not legit. if you do not have proof or you do not own the hacks, leave. if it is bad the creators will get in to this.

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey i know the creator were best friends ok and im not sharing information with you guys you guys are blood thirsty freaks who just want trol and get rich and were just trying to be nice and help people out by giving them free javascripts from my friend group so shut up now im done here yes unless your  nice and except the fact that were helping you and giving you free things

**Comment by isthatyourfaceoryouassicanttell** [comment]
im done here

**Comment by isthatyourfaceoryouassicanttell** [comment]
pizza your good

**Comment by isthatyourfaceoryouassicanttell** [comment]
steve did not do anything he is a copywriter and is just trying to get famous and trol people and take things from people

**Comment by isthatyourfaceoryouassicanttell** [comment]
pazza your are good to go every thing for for steve

**Comment by isthatyourfaceoryouassicanttell** [comment]
steve is a fake little leach feeding off the big guys

**Comment by isthatyourfaceoryouassicanttell** [comment]
pazza you have email

**Comment by isthatyourfaceoryouassicanttell** [comment]
heres mine evanchristensenkunz@gmail.com

**Comment by pazza223** [comment]
ya, but can not chat throgh it right now

**Comment by pazza223** [comment]
idk why, just google being google and wanting like 20000 step varifacation

**Comment by isthatyourfaceoryouassicanttell** [comment]
lol

**Comment by bigguystevieb1** [comment]
@isthatyourfaceoryouassicanttell dude stfu

**Comment by Blooket-dude** [comment]
> You realize right i can hack and I know a guy a good friend who could hack your account delete everything and take everything from you if he wanted to so I highly recommended SHUTTING UP BEFORE I HACK YOU OK SO JUST STOP IF YOU DON'T STOP FIRST 1 day ban THEN 1 week of ban THEN I WILL BAN YOUR ACCOUNT FOR EVER.

dude is that a threat? if he wants his code removed you should remove it! Dont argue or I will take legal actions!

**Comment by Blooket-dude** [comment]
@bigguystevieb1 I got you! Tell me if they are starting something again! I will try my best to help!

**Comment by Blooket-dude** [comment]
@bigguystevieb1 what scripts are yours.

**Comment by colbymcdaniel** [comment]
how are they in breach of copyrights

**Comment by Blooket-dude** [comment]
@colbymcdaniel what u mean

**Comment by colbymcdaniel** [comment]
yall had a hole argument about being in breach of copyright so I was asking were yall did

**Comment by Blooket-dude** [comment]
@colbymcdaniel  i didnt do anyhting Im trying to help my friend because someone is using his code without putting credits which is illegal becuase of copyright

**Comment by colbymcdaniel** [comment]
@Blooket-dude o i was just wondering what yall were talking about

**Comment by Blooket-dude** [comment]
its all good

**Comment by colbymcdaniel** [comment]
@Blooket-dude ok thanks

**Comment by Blooket-dude** [comment]
no problem

**Comment by pazza223** [comment]
to me, the repo is empty. idk how to get the hacks. how do i get them?

**Comment by colbymcdaniel** [comment]
to tell you the truth I don't know ether

**Comment by Blooket-dude** [comment]
@colbymcdaniel @pazza223 go to my repo and get them.

**Comment by pazza223** [comment]
??? dose this mean that you made them

**Comment by Blooket-dude** [comment]
made what?

**Comment by pazza223** [comment]
the hacks
in the repo

**Comment by Blooket-dude** [comment]
in my repo?

**Comment by pazza223** [comment]
yes

**Comment by pazza223** [comment]
the blooket hacks gui is made by basil...

**Comment by Blooket-dude** [comment]
Yeah I made some of them but if you read the README.md it will say that some of the blooket hack are from diffrent people so i put credits in. Some of the hacks I made from scratch. the blooket hack h=gui thing is made by someone called basil he makes diffrent types of hacks

**Comment by pazza223** [comment]
oh, cool, i give star

**Comment by Hankypoo7** [comment]
> @colbymcdaniel i didnt do anyhting Im trying to help my friend because someone is using his code without putting credits which is illegal becuase of copyright

Wich code did I copy from the biggie steve guy

**Comment by colbymcdaniel** [comment]
i don't know

**Comment by Blooket-dude** [comment]
@Hankypoo7  I dont know because he didnt tell me. but if you wanna keep coming at me I can make a report that your using someones code without their permission or at least give credits

**Comment by Blooket-dude** [comment]
@pazza223 you starred my repo?

**Comment by pazza223** [comment]
@Blooket-dude yes

**Comment by colbymcdaniel** [comment]
who are you going to report

**Comment by Blooket-dude** [comment]
@pazza223  thank you so much!

**Comment by Blooket-dude** [comment]
@colbymcdaniel  I will report @Hankypoo7.

**Comment by Hankypoo7** [comment]
blooket dude i didnt steal anything

**Comment by pazza223** [comment]
i star basicly all blooket hack repos i find good

**Comment by Blooket-dude** [comment]
@pazza223 ok

**Comment by Blooket-dude** [comment]
@Hankypoo7  I was told that you did steal something.

**Comment by Hankypoo7** [comment]
he just wants me to take my hacks down so that people will go to his page instead of mine

**Comment by colbymcdaniel** [comment]
@Blooket-dude  ok i just wanted to make sure you weren't talking about me

**Comment by Blooket-dude** [comment]
@colbymcdaniel no your good!

**Comment by colbymcdaniel** [comment]
thanks (=

**Comment by Hankypoo7** [comment]
Blooket dude ask him what i stole

**Comment by Hankypoo7** [comment]
ask him

**Comment by Hankypoo7** [comment]
for the tokens?

**Comment by Blooket-dude** [comment]
@Hankypoo7 if you did using something of his i dont really care. But if you did and you didnt give credits thats messed up. I will belive you this time but if i get another report of someone saying you stole something without giving credits im going to have to report you. You are fine for now but I will look farther into this and if i find out your lying well its not gonna be fun. im not thrating you im jsut trying to make this be a better place (=

**Comment by colbymcdaniel** [comment]
@Hankypoo7  what tokens

**Comment by Hankypoo7** [comment]
Look further into it

**Comment by Hankypoo7** [comment]
please

**Comment by Blooket-dude** [comment]
@Hankypoo7  if you need a make an issue on my repo and ask me if you can use the hacks i will most likely say yes as long as i get credits. I will def look further into it.

**Comment by colbymcdaniel** [comment]
@Hankypoo7  are you hiding something

**Comment by Hankypoo7** [comment]
token hack

**Comment by Blooket-dude** [comment]
@colbymcdaniel  he isnt

**Comment by Hankypoo7** [comment]
what could I be hiding

**Comment by Blooket-dude** [comment]
@Hankypoo7 You know what im not going to look further into it.

**Comment by colbymcdaniel** [comment]
@Blooket-dude  ok

**Comment by Hankypoo7** [comment]
why

**Comment by Hankypoo7** [comment]
Just asking

**Comment by Blooket-dude** [comment]
i know your not lying becuase when I asked you to give credits you gave me credits without any problems

**Comment by colbymcdaniel** [comment]
yah way

**Comment by Hankypoo7** [comment]
ok

**Comment by colbymcdaniel** [comment]
oooooooooooooooooh

**Comment by Blooket-dude** [comment]
@Hankypoo7 so your fine. sorry for the troubles but I will deal with @bigguystevieb1 and talk to him about this

**Comment by colbymcdaniel** [comment]
never mind

**Comment by Hankypoo7** [comment]
ok thanks

**Comment by colbymcdaniel** [comment]
@Hankypoo7 can i help

**Comment by Blooket-dude** [comment]
@Hankypoo7 no problem! Also can you make me a contributer on your repo I would love to help make your stuff more organized and add more hacks when I make more, if thats fine with you?

**Comment by Hankypoo7** [comment]
sure, but please dont make anything bad, I'm trusting you guys

**Comment by Blooket-dude** [comment]
I wont you can trust me!

**Comment by colbymcdaniel** [comment]
thanks and i wont

**Comment by colbymcdaniel** [comment]
just tell me what to do and ill figure it out

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
i gtg ill be back on at 4 or before

**Comment by Blooket-dude** [comment]
ok

**Comment by Blooket-dude** [comment]
I have to go

**Comment by colbymcdaniel** [comment]
ok

**Comment by colbymcdaniel** [comment]
im back

**Comment by Blooket-dude** [comment]
ight

**Comment by Hankypoo7** [comment]
talk on the other chat
