### ISSUE TITLE
Chat here

### ISSUE THREAD

**Issue by Hankypoo7** [Hankypoo7/Blooket-hacks-Hankypoo7-#9]
yeah

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey hows the ixl going

**Comment by Hankypoo7** [comment]
im sorry
I dont understand what a ixl is can you explain it to me

**Comment by colbymcdaniel** [comment]
its basically Kahoot but without the fun

**Comment by colbymcdaniel** [comment]
@Hankypoo7 its basically Kahoot but without the fun

**Comment by Hankypoo7** [comment]
ok

**Comment by isthatyourfaceoryouassicanttell** [comment]
its a learning platform

**Comment by Hankypoo7** [comment]
got it

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey can you try to fix box spam since i don't know how to fix them

**Comment by Blooket-dude** [comment]
@Hankypoo7 get the script from me if you want

**Comment by Blooket-dude** [comment]
give credits tho

**Comment by Hankypoo7** [comment]
ok

**Comment by Blooket-dude** [comment]
@Hankypoo7 why cant I add files?

**Comment by Blooket-dude** [comment]
I need to add more files to make it better

**Comment by colbymcdaniel** [comment]
What's up?

**Comment by colbymcdaniel** [comment]
@Blooket-dude what's up?

**Comment by Blooket-dude** [comment]
@colbymcdaniel sup

**Comment by colbymcdaniel** [comment]
@Blooket-dude  what were yall talking about

**Comment by Blooket-dude** [comment]
nothing I just could edit anything but i fixed it.

**Comment by colbymcdaniel** [comment]
ok

**Comment by colbymcdaniel** [comment]
@Blooket-dude just tell me if you need any help I will try and figure it out

**Comment by Blooket-dude** [comment]
@colbymcdaniel  ok thanks!

-Blooket-dude

**Comment by colbymcdaniel** [comment]
no problem

**Comment by bigguystevieb1** [comment]
@Blooket-dude look at ur repository

**Comment by Hankypoo7** [comment]
wait u cant edit my thing?

**Comment by Blooket-dude** [comment]
@Hankypoo7 i fixed it! Also go to the new issue on my repo this dude is saying he will use my hacks after i said not to.

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
Blooket dude I cant chat on your thing

**Comment by Hankypoo7** [comment]
can you make it where I can talk so I can Back you up

**Comment by Blooket-dude** [comment]
what do you mean you cant chat?

**Comment by Blooket-dude** [comment]
what does it say?

**Comment by Hankypoo7** [comment]
it says "You can't perform this action at this time."

**Comment by Blooket-dude** [comment]
give me a sec

**Comment by Blooket-dude** [comment]
I invited you as a collaborator accept the invite. maybe that will let you chat?

**Comment by Blooket-dude** [comment]
@Hankypoo7

**Comment by Hankypoo7** [comment]
ok

**Comment by Blooket-dude** [comment]
did you accept it?

**Comment by Blooket-dude** [comment]
I @ you in the chat where we are

**Comment by Hankypoo7** [comment]
yeah i see

**Comment by Blooket-dude** [comment]
ok

**Comment by colbymcdaniel** [comment]
what yall talking about?

**Comment by Snowflake-Blooket-dude** [comment]
what do you mean?

-Snowflake

**Comment by colbymcdaniel** [comment]
ok

**Comment by Hankypoo7** [comment]
This guy stole her hacks so we went to stop him

**Comment by Hankypoo7** [comment]
you

**Comment by colbymcdaniel** [comment]
whats up then

**Comment by Hankypoo7** [comment]
but hi

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7  I can help code hacks if you ever need help

**Comment by Hankypoo7** [comment]
ok thank you

**Comment by colbymcdaniel** [comment]
Mabey if you can in infinite cion  glitch for global blooket

**Comment by colbymcdaniel** [comment]
thanks yeah i will help you with any thing i can figure out

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel I could code that, but it wouldn't work becuase due to getting tokens being server side it will only say you have a certain amount but you really dont have that amount.


-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  oh ok how about some ixl hacks I've heard that there are some

**Comment by Snowflake-Coder-H2o** [comment]
what is an ixl hack? @colbymcdaniel?

-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o I don't know I heard Hankypoo7 and @blooket-dude were talking about it so I was  seeing if you know

**Comment by Snowflake-Coder-H2o** [comment]
I just changed my name. 

-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  really you have to account I just say you and hankypoo7 talking but then hankypoo7 said something about ixl hack so I was wanting to know

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Oh ok.Yeah well I have no Idea what an ixl hack is. 


-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  it's ok I was just wandering about what it is.

**Comment by Snowflake-Coder-H2o** [comment]
Thanks!

-SnowFlakeΨ

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey whats up

**Comment by isthatyourfaceoryouassicanttell** [comment]
o hey guys the ixl hack basically i want a hack that gets me all my questions right ixl is a learning program and just search it up and do your course just see it it will make alot of sense then

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel @isthatyourfaceoryouassicanttell I dont know if it is possible to code. It might be. I will make a code and test it give me a couple of hours!


--SnowFlakeΨ

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o ok thanks for trying it

**Comment by Snowflake-Coder-H2o** [comment]
No problem!

-Snowflake

**Comment by Hankypoo7** [comment]
oh yeah thank you

**Comment by Hankypoo7** [comment]
im at school now lol

**Comment by Hankypoo7** [comment]
> Mabey if you can in infinite cion glitch for global blooket

yeah that's impossible because it is encrypted into blooket's database, instead of the users.

**Comment by Hankypoo7** [comment]
bet yeah that would be cool

**Comment by colbymcdaniel** [comment]
do yall have iney ixl hacks though

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o @Hankypoo7 do yall have some ixl hacks so you can get all the questions right

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel  Im currently working on it.

**Comment by colbymcdaniel** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
- im working on them right now

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o just tell me when your done (=

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  Do you know what would be cool a Starr test hack?

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel what do you mean?

**Comment by colbymcdaniel** [comment]
the star test it would be cool/illegal if you could hack it

**Comment by colbymcdaniel** [comment]
how about ix hacks?

**Comment by isthatyourfaceoryouassicanttell** [comment]
heyyyyyyy

**Comment by isthatyourfaceoryouassicanttell** [comment]
why did you change the coin hack

**Comment by isthatyourfaceoryouassicanttell** [comment]
why

**Comment by isthatyourfaceoryouassicanttell** [comment]
NOW IT DOESN'T WORKKKKKKKKKKKKKKKKKKKK !!!!!!!!!! that is the number one thing on this site and you guys have to break the working one like come on

**Comment by isthatyourfaceoryouassicanttell** [comment]
now i have to make another one :(((((((((((((((((((((((:(:(:(:(:(:(

**Comment by isthatyourfaceoryouassicanttell** [comment]
now here i fixed it

**Comment by colbymcdaniel** [comment]
@isthatyourfaceoryouassicanttell  what did you fix

**Comment by colbymcdaniel** [comment]
@isthatyourfaceoryouassicanttell can you make me an ixl hack?

**Comment by colbymcdaniel** [comment]
hello?

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell what are ou talking about?


-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  i think he is mad about yall changing the coin thing i don't know

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel @isthatyourfaceoryouassicanttell @Hankypoo7 @ollj429 @Hankypoo7 Should I keep my Blooket-Hack  repo public or should I make it private

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel what do you mean changing the coin thing?

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  you should make it privet and i don't know he was just talking about a coin thing and how yall changed it

**Comment by Snowflake-Coder-H2o** [comment]
I made my repo Private becuase of it being too heated in the issues.


-Snow

**Comment by Snowflake-Coder-H2o** [comment]
it is now Public.

-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  ok you do you

**Comment by Snowflake-Coder-H2o** [comment]
Alright! @colbymcdaniel Do you play blooket?


-Snow

**Comment by colbymcdaniel** [comment]
yes yes i do

**Comment by colbymcdaniel** [comment]
yes i do @Snowflake-Coder-H2o

**Comment by Snowflake-Coder-H2o** [comment]
do you need any hacks?

-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  yeah that would help me out some

**Comment by Snowflake-Coder-H2o** [comment]
What hacks do you want. I might have some already coded. 

-Snow

**Comment by colbymcdaniel** [comment]
the coin hack and any other one you think is useful

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o the coin hack and any other one you think is usefu

**Comment by Snowflake-Coder-H2o** [comment]
Ok, I will be making a brand new repo and filling it with useful hacks. If you want to you can look through all of the hacks and the ones you want you can take.

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o ok, thanks! your one of the nicest person on here

**Comment by Snowflake-Coder-H2o** [comment]
Thanks that means alot to me!


-Snow

**Comment by colbymcdaniel** [comment]
no thanks to you @Snowflake-Coder-H2o

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel what do you mean by "no thanks to you"?


-Snow

**Comment by colbymcdaniel** [comment]
i was basically saying that i am more thankful it just a nice gesture

**Comment by Snowflake-Coder-H2o** [comment]
Oh ok! 


-Snow

**Comment by Hankypoo7** [comment]
hi I'm back

**Comment by Hankypoo7** [comment]
ok ill check it out and star it snowflake

**Comment by colbymcdaniel** [comment]
same

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Thanks! I also make you a collaberator. Just so you can help people out. Also Hanky make sure to star it and make sure to have the watch parth check to all!

-Snow

**Comment by colbymcdaniel** [comment]
@Hankypoo7 were is it at again

**Comment by Hankypoo7** [comment]
ok i got it

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Thanks! I also make you a collaborator. Just so you can help people out. Also, Hanky make sure to star it and make sure to have the watch part checked to all! Also If people need help and I'm not arround, can you please help them.

-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o were is it so i can star it btw

**Comment by Hankypoo7** [comment]
https://github.com/Snowflake-Coder-H2o/Blooket-Hack/issues/1

**Comment by Hankypoo7** [comment]
thats the link

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel go to my github profile page where it shows all of my repos. then click the newest one

**Comment by colbymcdaniel** [comment]
ok

**Comment by Hankypoo7** [comment]
oops
I meant this one
https://github.com/Snowflake-Coder-H2o/Blooket-Hack

**Comment by colbymcdaniel** [comment]
did it

**Comment by Snowflake-Coder-H2o** [comment]
Thank you so much!


-Snow

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7

**Comment by colbymcdaniel** [comment]
no problem

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7

**Comment by colbymcdaniel** [comment]
i also stared it btw

**Comment by Snowflake-Coder-H2o** [comment]
Thanks!

-Snow

**Comment by colbymcdaniel** [comment]
no problem

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7

**Comment by Hankypoo7** [comment]
yeah

**Comment by Hankypoo7** [comment]
what up

**Comment by Snowflake-Coder-H2o** [comment]
Do you have any questions people might want to know about me or about what I code or anything like that?


-Snow

**Comment by Hankypoo7** [comment]
uh lemmie think

**Comment by Snowflake-Coder-H2o** [comment]
Ok!

-Snow

**Comment by Hankypoo7** [comment]
how about why you want to code

**Comment by Snowflake-Coder-H2o** [comment]
Ok Just give me some questions and I'm going to answer them in the new repo

**Comment by Snowflake-Coder-H2o** [comment]
Just make a list. 


-Snow

**Comment by Hankypoo7** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7  You making a list?

-Snow

**Comment by Hankypoo7** [comment]
yeah

**Comment by Hankypoo7** [comment]
gimmie a couple minutes

**Comment by Snowflake-Coder-H2o** [comment]
Ok. 

-Snow

**Comment by Hankypoo7** [comment]
what makes you want to code?
what are your plans for the future?
how often will you be updating the codes?
are you looking for people to help you code?
what is the goal you are looking to reach?

**Comment by Snowflake-Coder-H2o** [comment]
ok i will answer them right now

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
btw I fixed the hack menu to make it updated

**Comment by Snowflake-Coder-H2o** [comment]
I know I seen that thanks.

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
i gtg ill be back in like 2 minutes

**Comment by Snowflake-Coder-H2o** [comment]
ok

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o and you might want to add what you are making in the future

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel What do you mean?


-Snow

**Comment by colbymcdaniel** [comment]
like you should add what your project is in the future

**Comment by Snowflake-Coder-H2o** [comment]
What do ou mean by future project?


-Snow

**Comment by colbymcdaniel** [comment]
if you have any thing/project you should list it in the repo

**Comment by Snowflake-Coder-H2o** [comment]
I dont really have any that come to mind

**Comment by colbymcdaniel** [comment]
i mean when you do or when it comes to mind

**Comment by Snowflake-Coder-H2o** [comment]
I will! Thanks for the suggestion.


-Snow

**Comment by colbymcdaniel** [comment]
no problem

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
@colbymcdaniel do you know how to hack?

**Comment by Hankypoo7** [comment]
to code it I mean

**Comment by colbymcdaniel** [comment]
I'm taking a course to learn how to why whats up

**Comment by colbymcdaniel** [comment]
bell at school is about to ring i won't respond for a minute

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Wanna play a blooket?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 @colbymcdaniel Wanna play Blooket?

**Comment by Hankypoo7** [comment]
im back sure

**Comment by Hankypoo7** [comment]
oh wait i can at like 540 ct or something maybe

**Comment by Hankypoo7** [comment]
do you guys have any questions about me?

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 wanna do a Blooket?

**Comment by Hankypoo7** [comment]
I cant rn but maybe at 540 ct

**Comment by Hankypoo7** [comment]
i gotta eat

**Comment by Snowflake-Coder-H2o** [comment]
ok!

**Comment by Hankypoo7** [comment]
im back

**Comment by Hankypoo7** [comment]
o wait

**Comment by Hankypoo7** [comment]
sorry my family wants to watch a movie before my sister goes to bed

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Your good!


-Snow

**Comment by colbymcdaniel** [comment]
just got back whats new

**Comment by colbymcdaniel** [comment]
wait nevermind got to go again

**Comment by isthatyourfaceoryouassicanttell** [comment]
hey guys if someone wants to fix get all questions right that would be nice i can't right now but i might be able to tomorrow.

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell on my repo or on this one?

**Comment by Hankypoo7** [comment]
this one I think

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Its fixed.

**Comment by bigguystevieb1** [comment]
Yall are stupid

**Comment by colbymcdaniel** [comment]
thats mean

**Comment by Hankypoo7** [comment]
Thanks for fixing it @Snowflake-Coder-H2o

**Comment by colbymcdaniel** [comment]
@Hankypoo7 who are you talking to

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 I just taught myself


-Snow

**Comment by Hankypoo7** [comment]
cool

**Comment by colbymcdaniel** [comment]
anything new

**Comment by colbymcdaniel** [comment]
@Hankypoo7 anything new.

**Comment by colbymcdaniel** [comment]
@isthatyourfaceoryouassicanttell are you still making the ixl hack if your done can i get it

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel I tried coding one But i Failed.

**Comment by colbymcdaniel** [comment]
ok well thanks for trying

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel No problem

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  any other thing happening that i should know about

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel What?

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o i was just asking whats happened while i was gone

**Comment by colbymcdaniel** [comment]
ok then nevermind

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel @isthatyourfaceoryouassicanttell @Hankypoo7 If you need me @ me because im going to be coding hacks!

-Snow

**Comment by colbymcdaniel** [comment]
ok

**Comment by Hankypoo7** [comment]
ok got it

**Comment by Snowflake-Coder-H2o** [comment]
ok

**Comment by colbymcdaniel** [comment]
hay @Hankypoo7 what's happened while i was gone

**Comment by colbymcdaniel** [comment]
@Hankypoo7  i was taking the cba at my school

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 @colbymcdaniel

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o whats up

**Comment by Snowflake-Coder-H2o** [comment]
Wanna play a blooket?

**Comment by colbymcdaniel** [comment]
shure

**Comment by colbymcdaniel** [comment]
whats the code

**Comment by Snowflake-Coder-H2o** [comment]
ok the join code is 580655

**Comment by colbymcdaniel** [comment]
im toast btw

**Comment by Snowflake-Coder-H2o** [comment]
ok, I'm going to show you all of the blooks I have legit. I have everything except for Halloween and the chromas.

-Snow

**Comment by Snowflake-Coder-H2o** [comment]
ok?


-Snow

**Comment by colbymcdaniel** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
I have every blook in the game except for the ones I said I didn't have.

**Comment by Snowflake-Coder-H2o** [comment]
Also no hacking.

**Comment by colbymcdaniel** [comment]
i basically the exact thing with the skins

**Comment by Snowflake-Coder-H2o** [comment]
So you have every blook that you can currently get?

**Comment by Snowflake-Coder-H2o** [comment]
you playing the game?

**Comment by colbymcdaniel** [comment]
yes and yes

**Comment by Snowflake-Coder-H2o** [comment]
ok

**Comment by Snowflake-Coder-H2o** [comment]
your score isnt going up thats why im asking

**Comment by colbymcdaniel** [comment]
fair

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  i'm going to have to go my bell is about to ring you win

**Comment by Snowflake-Coder-H2o** [comment]
Ok !


-Snow

**Comment by Hankypoo7** [comment]
i gtg ill be on tonight

**Comment by Snowflake-Coder-H2o** [comment]
ok

**Comment by colbymcdaniel** [comment]
whats up im back

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o did you use hacks last night when we were playing booket

**Comment by Snowflake-Coder-H2o** [comment]
No. Why?

-Snow

**Comment by colbymcdaniel** [comment]
just wondering.

**Comment by Snowflake-Coder-H2o** [comment]
Oh ok. 

-Snow

**Comment by colbymcdaniel** [comment]
umm anything new I should know about

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o umm anything new I should know about

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel Not that I know of!


-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o  well you wanna play blooket

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel  in a couple minutes

**Comment by Snowflake-Coder-H2o** [comment]
i have to fix one of the codes

**Comment by Snowflake-Coder-H2o** [comment]
@colbymcdaniel i fixed the code wanna pla?

**Comment by colbymcdaniel** [comment]
cant play it 3:30 i will play at 4:10

**Comment by Snowflake-Coder-H2o** [comment]
ok

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o what's new?

**Comment by Hankypoo7** [comment]
not much

**Comment by isthatyourfaceoryouassicanttell** [comment]
which one is out to date which one is not working???????????

**Comment by colbymcdaniel** [comment]
@isthatyourfaceoryouassicanttell I do not know

**Comment by Snowflake-Coder-H2o** [comment]
@isthatyourfaceoryouassicanttell I don't know. But my hacks are probably outdated. So your might be. But like I said I have no clue. I'm in the process of fixing them now.  @Hankypoo7 Want me to fix your hacks when I fix mine?

-Snow

**Comment by colbymcdaniel** [comment]
@Snowflake-Coder-H2o @isthatyourfaceoryouassicanttell @Hankypoo7 the set coins on the tower of doom isn't working btw I looked into it but couldn't figure it out sorry

**Comment by colbymcdaniel** [comment]
actually I don't believe any of the dower of doom hacks are working

**Comment by Hankypoo7** [comment]
ok ill try to fix them 
and yes pls snowflake thanks

**Comment by Snowflake-Coder-H2o** [comment]
@Hankypoo7 Ok I will try to fix them!

-Snow

**Comment by Hankypoo7** [comment]
thanks

**Comment by colbymcdaniel** [comment]
@Hankypoo7 how do you make something private from public on here

**Comment by colbymcdaniel** [comment]
@Hankypoo7  how do you make something private from public on here and there is someone claiming to be the first blooket 
hacks

**Comment by colbymcdaniel** [comment]
and btw some of the crazy kingdom hacks aren't working.

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
wich ones are broken?

**Comment by colbymcdaniel** [comment]
the ones are skip guest and skip tax and he goes by gbasil.dev/blooket

**Comment by colbymcdaniel** [comment]
@Hankypoo7 the ones are skip guest and skip tax and he goes by gbasil.dev/blooket

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
thanks

**Comment by colbymcdaniel** [comment]
no problem

**Comment by Hankypoo7** [comment]
ill try to fix them within the next day

**Comment by colbymcdaniel** [comment]
@Hankypoo7 don't use the hacks one of my friends tested them out he got banned

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
wich one

**Comment by colbymcdaniel** [comment]
@Hankypoo7  the one that claims to be the first blooket hack i got banned for trying it

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
im really sorry for you getting banned, if there is anything I can do let me know

**Comment by Hankypoo7** [comment]
I deleted the hack menu, wich is the one I think

**Comment by Hankypoo7** [comment]
ok

**Comment by Hankypoo7** [comment]
I also put up a warning in the read.me

**Comment by Hankypoo7** [comment]
thanks tho, and would you want to help run this page with me and @Snowflake-Coder-H2o and @isthatyourfaceoryouassicanttell ?

**Comment by Hankypoo7** [comment]
igtg but ill send u an invite

**Comment by Hankypoo7** [comment]
I invited you

**Comment by Hankypoo7** [comment]
I took it down

**Comment by Hankypoo7** [comment]
i gtg tho ill be back in a bit

**Comment by colbymcdaniel** [comment]
it was the person whom said they made the first hacks not your hacks

**Comment by Hankypoo7** [comment]
oh

**Comment by Hankypoo7** [comment]
wait so my hacks are ok?

**Comment by Hankypoo7** [comment]
or do they get you banned

**Comment by colbymcdaniel** [comment]
your hacks are ok but the one I told you about arent the gbasil.dev/blooket

**Comment by Hankypoo7** [comment]
oh ok thanks

**Comment by colbymcdaniel** [comment]
yeah, no problem.

**Comment by Hankypoo7** [comment]
Ill also put a warning for that website too

**Comment by colbymcdaniel** [comment]
ok

**Comment by Hankypoo7** [comment]
do you want to collab I innvited you to this resporitory

**Comment by colbymcdaniel** [comment]
I just started on here a month ago were is this repository

**Comment by Hankypoo7** [comment]
same but uh i gtg ill msg you in a bit

**Comment by colbymcdaniel** [comment]
ok and what dose gtg mean

**Comment by Hankypoo7** [comment]
I got to go

**Comment by colbymcdaniel** [comment]
oh ok never mind you can go

**Comment by Hankypoo7** [comment]
this is a resporitory. I invited you so try to accept it

**Comment by colbymcdaniel** [comment]
how do i accept it

**Comment by Hankypoo7** [comment]
uh lemmie see

**Comment by Hankypoo7** [comment]
To accept the invitation:
Navigate to the Connection tab.
Click Accept invitation.
Paste the invitation code. Paste the invitation code that you received from your partner.
Click Next.
Select the repository where you want to sync issues.
Click Confirm.

**Comment by Hankypoo7** [comment]
thats what google said

**Comment by Hankypoo7** [comment]
it'll let you edit stuff on this project

**Comment by colbymcdaniel** [comment]
cant talk but thank you I will figure it out later thanks though

**Comment by Hankypoo7** [comment]
ok

**Comment by colbymcdaniel** [comment]
I can't find the connection tab
